[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/ory/dockertest"
  version = "3.x"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
